# Generated by Django 2.2.3 on 2019-08-30 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busno', models.CharField(max_length=150)),
                ('busplatenumber', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminfirstname', models.CharField(max_length=150, null=True)),
                ('adminlastname', models.CharField(max_length=150, null=True)),
                ('companyname', models.CharField(max_length=150, null=True, unique=True)),
                ('companyemail', models.CharField(max_length=150, null=True, unique=True)),
                ('companypassword', models.CharField(max_length=150, null=True)),
                ('companyconfirmpassword', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cus_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=150)),
                ('confirmpassword', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='xt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_time', models.DateTimeField(null=True)),
                ('x_name', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationname', models.CharField(max_length=150, null=True)),
                ('companyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bussystem.Company')),
            ],
        ),
        migrations.CreateModel(
            name='routee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_no', models.CharField(max_length=150)),
                ('Time', models.CharField(max_length=150, null=True)),
                ('price', models.FloatField(max_length=8, null=True)),
                ('booked_seats', models.CharField(max_length=300, null=True)),
                ('remaining_seats', models.CharField(max_length=300, null=True)),
                ('bus_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bussystem.BusDetail')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bussystem.Company')),
                ('from_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_froom_fore', to='bussystem.Station')),
                ('to_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='but_to_fore', to='bussystem.Station')),
            ],
        ),
        migrations.AddField(
            model_name='busdetail',
            name='bsid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bussystem.Company'),
        ),
        migrations.CreateModel(
            name='Bt',
            fields=[
                ('bt_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, null=True)),
                ('email', models.CharField(max_length=150, null=True)),
                ('fnames', models.CharField(max_length=150, null=True)),
                ('lnames', models.CharField(max_length=150, null=True)),
                ('address', models.CharField(max_length=150, null=True)),
                ('city', models.CharField(max_length=150, null=True)),
                ('passwords', models.CharField(max_length=150, null=True)),
                ('companyidd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bussystem.Company')),
            ],
        ),
        migrations.CreateModel(
            name='bootticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('cnic', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('amount', models.FloatField(null=True)),
                ('seatno', models.IntegerField(null=True)),
                ('noofseats', models.CharField(max_length=150, null=True)),
                ('route_forign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_for', to='bussystem.routee')),
            ],
        ),
    ]
