# Generated by Django 2.2.3 on 2019-08-01 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busno', models.CharField(max_length=150, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('com_id', models.AutoField(primary_key=True, serialize=False)),
                ('adminfirstname', models.CharField(max_length=150, null=True, unique=True)),
                ('adminlastname', models.CharField(max_length=150, null=True)),
                ('companyname', models.CharField(max_length=150, null=True, unique=True)),
                ('companyemail', models.CharField(max_length=150, null=True, unique=True)),
                ('companypassword', models.CharField(max_length=150, null=True)),
                ('companyconfirmpassword', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='xt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_time', models.DateTimeField(null=True)),
                ('x_name', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationname', models.CharField(max_length=150, null=True, unique=True)),
                ('companyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bussystem.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busno', models.CharField(max_length=150, null=True)),
                ('bs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bussystem.BusDetail')),
                ('com', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bussystem.Company')),
                ('fromm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_froom_fore', to='bussystem.Station')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='but_to_fore', to='bussystem.Station')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cus_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50, unique=True)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('confirmpassword', models.CharField(max_length=150)),
                ('cus_foreign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bussystem.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Bt',
            fields=[
                ('bt_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=150, null=True)),
                ('email', models.CharField(max_length=150, null=True, unique=True)),
                ('fnames', models.CharField(max_length=150, null=True)),
                ('lnames', models.CharField(max_length=150, null=True)),
                ('address', models.CharField(max_length=150, null=True)),
                ('city', models.CharField(max_length=150, null=True)),
                ('passwords', models.CharField(max_length=150, null=True)),
                ('company_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bussystem.Company')),
            ],
        ),
    ]
