# Generated by Django 2.2.3 on 2019-07-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='xt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_time', models.DateTimeField(null=True)),
                ('x_name', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
