# Generated by Django 2.2.3 on 2019-08-20 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bussystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bootticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('phone', models.IntegerField()),
                ('cnic', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.FloatField()),
                ('noofseats', models.IntegerField()),
                ('seatno', models.IntegerField()),
                ('route_forign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_for', to='bussystem.routee')),
            ],
        ),
    ]
