# Generated by Django 2.2.3 on 2019-08-30 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bussystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routee',
            name='booked_seats',
        ),
        migrations.RemoveField(
            model_name='routee',
            name='remaining_seats',
        ),
    ]
