# Generated by Django 2.2.3 on 2019-08-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bussystem', '0002_busdetail_busplatenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='pic',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
