# Generated by Django 2.2.3 on 2019-08-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussystem', '0002_bootticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootticket',
            name='username',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
