# Generated by Django 2.2.3 on 2019-08-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussystem', '0002_auto_20190831_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='routee',
            name='booked_seats',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='routee',
            name='remaining_seats',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
