# Generated by Django 2.2.3 on 2019-08-17 10:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bussystem', '0003_company_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='pic',
        ),
    ]
