# Generated by Django 2.2.3 on 2019-08-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussystem', '0003_auto_20190820_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootticket',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bootticket',
            name='cnic',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bootticket',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='bootticket',
            name='noofseats',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bootticket',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bootticket',
            name='seatno',
            field=models.IntegerField(null=True),
        ),
    ]
