# Generated by Django 2.2.3 on 2019-08-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussystem', '0003_auto_20190831_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routee',
            name='remaining_seats',
            field=models.IntegerField(null=True),
        ),
    ]
