# Generated by Django 2.2.3 on 2019-08-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bussystem', '0004_remove_company_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='busno',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
