# Generated by Django 2.2.3 on 2019-08-23 12:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussystem', '0004_auto_20190820_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootticket',
            name='pieces',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), size=None), default=1, size=None),
            preserve_default=False,
        ),
    ]
