# Generated by Django 2.2.3 on 2019-08-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussystem', '0005_auto_20190831_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootticket',
            name='noofseats',
            field=models.CharField(max_length=1500, null=True),
        ),
    ]
