# Generated by Django 2.2.3 on 2019-08-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussystem', '0006_auto_20190823_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootticket',
            name='noofseats',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
