# Generated by Django 2.2.3 on 2019-08-17 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('bussystem', '0007_remove_route_fromm'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='fromm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='bus_froom_fore', to='bussystem.Station'),
        ),
        migrations.AlterField(
            model_name='route',
            name='bus_no',
            field=models.CharField(default=1, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
