# Generated by Django 2.2.3 on 2019-08-17 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('bussystem', '0008_auto_20190817_0359'),
    ]

    operations = [
        migrations.CreateModel(
            name='routee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_no', models.CharField(max_length=150, unique=True)),
                ('Time', models.CharField(max_length=150, null=True)),
                ('price', models.FloatField(max_length=8, null=True)),
                ('bs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                         to='bussystem.BusDetail')),
                ('com',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bussystem.Company')),
                ('fromm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                            related_name='bus_froom_fore', to='bussystem.Station')),
                ('to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                         related_name='but_to_fore', to='bussystem.Station')),
            ],
        ),
        migrations.DeleteModel(
            name='Route',
        ),
    ]
