# Generated by Django 2.2.3 on 2019-08-17 11:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bussystem', '0009_auto_20190817_0403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routee',
            name='bs',
        ),
        migrations.RemoveField(
            model_name='routee',
            name='com',
        ),
        migrations.RemoveField(
            model_name='routee',
            name='fromm',
        ),
        migrations.RemoveField(
            model_name='routee',
            name='to',
        ),
    ]
