# Generated by Django 2.2.3 on 2019-08-30 20:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bussystem', '0009_auto_20190831_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(default=uuid.uuid1, max_length=100, unique=True),
        ),
    ]
