# Generated by Django 2.2.3 on 2019-08-17 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('bussystem', '0010_auto_20190817_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='routee',
            name='bus_route',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bussystem.BusDetail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routee',
            name='com_route',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='bussystem.Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routee',
            name='from_route',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='bus_froom_fore', to='bussystem.Station'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routee',
            name='to_route',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='but_to_fore',
                                    to='bussystem.Station'),
            preserve_default=False,
        ),
    ]
