# Generated by Django 2.2.3 on 2019-11-24 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bussystem', '0011_auto_20190831_0150'),
    ]

    operations = [
        migrations.CreateModel(
            name='buyticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('cnic', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('amount', models.FloatField(null=True)),
                ('noofseats', models.CharField(max_length=1500, null=True)),
                ('route_forign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_for_buy_ticket', to='bussystem.routee')),
            ],
        ),
    ]
