# Generated by Django 2.2.3 on 2019-08-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bussystem', '0011_auto_20190817_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busdetail',
            name='busno',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='busdetail',
            name='busplatenumber',
            field=models.CharField(default=2, max_length=150),
            preserve_default=False,
        ),
    ]
