# Generated by Django 2.2.3 on 2019-08-17 11:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bussystem', '0012_auto_20190817_0434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routee',
            old_name='bus_route',
            new_name='bus_details',
        ),
        migrations.RenameField(
            model_name='routee',
            old_name='com_route',
            new_name='company_name',
        ),
    ]
