# Generated by Django 2.2.3 on 2019-11-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussystem', '0012_buyticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='routee',
            name='buy_seats',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
