# Generated by Django 2.2.3 on 2019-08-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bussystem', '0013_auto_20190817_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routee',
            name='bus_no',
            field=models.CharField(max_length=150),
        ),
    ]
